version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/golang:1.20 
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t vadimso/todo2todo-go-app:latest .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-dockerhub-username/todo2:latest

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f kubernetes/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
